# Equipment Ledger

```{python}
#| echo: false
#| include: false
from sr6core.log_engine import inc, inc_many
```

### Combat

* Monofilament Whip `{python} inc('Nuyen', -1500)`
  * Fingertip Cyberarm Compartment Mount
* Amalgam Cestas (obtained in SRM 2083-18)
  * Personalized Grip `{python} inc('Nuyen', -200)`
* Krime Gloves (DA p. 30) `{python} inc('Nuyen', -1050)`
  * Personalized Grip `{python} inc('Nuyen', -200)`
* Ares Securetech SkinShield `{python} inc('Nuyen', -3000 * 1.05)`
  * Ballistic Hood
  * Concealable Holster (Ares Predator VI)
  * Ruthenium Armor Concealment System (R2)
* SecureTech Invisi-Shield `{python} inc('Nuyen', -5000)`
* Ares Predator VI `{python} inc('Nuyen', -1450)`
  * Silencer
  * Personalized Grip
  * Smartgun System
  * Variable Ammunition System
  * 50 Explosive Rounds `{python} inc('Nuyen', -100)`
  * 50 Krime Self Defense Rounds `{python} inc('Nuyen', -100)`
* Crimson Wasp x2 `{python} inc('Nuyen', -3000)`
* Red Fox `{python} inc('Nuyen', -2800)`
  * Smartgun System (Internal)
  * Peak-Discharge Laser Battery Clips x5 `{python} inc('Nuyen', -500)`
* Glitter Grenades x10 `{python} inc('Nuyen', -1000)`

### Matrix

* M-TOC II `{python} inc('Nuyen', -65000)`
  * Artillery Barrage `{python} inc('Nuyen', -200)`
  * ECM Warrior II `{python} inc('Nuyen', -200)`
  * Mobile Medic `{python} inc('Nuyen', -200)`
  * Sneak-Sneak `{python} inc('Nuyen', -200)`
  * Target Artist `{python} inc('Nuyen', -200)`
* Software Library 
  * Basic Programs
    * Baby Monitor `{python} inc('Nuyen', -100)`
    * Browse `{python} inc('Nuyen', -100)`
    * Edit `{python} inc('Nuyen', -100)`
    * **Emulator** `{python} inc_many(('Nuyen', -100),('Karma', -1))`
    * Encryption `{python} inc('Nuyen', -100)`
    * Signal Scrubber `{python} inc('Nuyen', -100)`
    * **Toolbox** `{python} inc_many(('Nuyen', -100),('Karma', -1))`
    * **Virtual Machine** `{python} inc_many(('Nuyen', -100),('Karma', -1))`
  * Hacking Programs
    * Decryption `{python} inc('Nuyen', -200)`
    * Defense Pods `{python} inc('Nuyen', -200)`
    * **Directional Shields** `{python} inc_many(('Nuyen', -200),('Karma', -1))`
    * Fork `{python} inc('Nuyen', -200)`
    * Hitchhiker `{python} inc('Nuyen', -200)`
    * **Nexus Protocol** `{python} inc_many(('Nuyen', -1000),('Karma', -1))`
    * Overclock `{python} inc('Nuyen', -200)`
    * Trace `{python} inc('Nuyen', -200)`
 * Rigger Programs
   * Smartsoft `{python} inc('Nuyen', -250)`  
   * Swarm `{python} inc('Nuyen', -250)`
   * Encryption (Rigger) `{python} inc('Nuyen', -250)`
* Autosofts
  * Biotech (R9) `{python} inc('Nuyen', -4500)`
  * **Clearsight (R9)** `{python} inc_many(('Nuyen', -4500),('Karma', -1))`
  * **Close Combat (R9)** `{python} inc_many(('Nuyen', -4500),('Karma', -1))`
  * Engineering (1, R9) `{python} inc('Nuyen', -4500)`
  * **Evasion (R9)** `{python} inc_many(('Nuyen', -4500),('Karma', -1))`
  * Knowledge `{python} inc('Nuyen', -1500)`
  * Language (1, R5) `{python} inc('Nuyen', -2500)`
  * **Maneuvering (1, R9)** `{python} inc_many(('Nuyen', -4500),('Karma', -1))`
  * Navigation (R9) `{python} inc('Nuyen', -4500)`
  * Performance (R9) `{python} inc('Nuyen', -4500)`
  * **Stealth (1, R9)** `{python} inc_many(('Nuyen', -4500),('Karma', -1))`
  * **Targeting (1, R9)** `{python} inc_many(('Nuyen', -4500),('Karma', -1))`
  * **Tracking (R9)** `{python} inc_many(('Nuyen', -4500),('Karma', -1))`
* Commlink Apps
  * Facial Scanner `{python} inc('Nuyen', -750)`
  * P-ICE Spines `{python} inc('Nuyen', -500)`
  * Personal Assistant (R6) `{python} inc('Nuyen', -600)`
  * Social HUD (R6) `{python} inc('Nuyen', -700)`
  * Thermal Mood Reading `{python} inc('Nuyen', -700)`
  * Vocal Tension Detection `{python} inc('Nuyen', -700)`
* Other
  * Mapsoft x4 `{python} inc('Nuyen', -400)`
  * Shopsoft x6 `{python} inc('Nuyen',-900)`
  * **Coding Facility** `{python} inc_many(('Nuyen',-5000),('Karma',-1))`

For autosofts that are specific, the character programs her derivative own based on the original version she bought above. This process takes 8 hours for knowledge and language autosofts, and 12 hours for all other autosofts. The cost is 1 karma for each of the derivative autosofts.

Software with karma costs have been learned via the **Software Emulator** echo.

### Vehicles & Drones

* MCT Gnat x5 `{python} inc('Nuyen', -4000)`
  * Realistic Features 4
  * Laser Jack

* Shiawase Bi-Drone Butler 
  * Drone Rack (Small) 
  * Wrist Shield 
  * Realistic Features 1
  * Increased Structural Integrity 2 
  * Secondary Propulsion (Rotor)
  * Increased Sensors 3
  * Retractible Skates x2
  * Hardpoint Small x2
    * Crimson Wasp x2
  * Built-In Utility Kit (Engineering)
  * Built-In MedKit
  * Accessories
    * Satellite Link
    * Laser Jack
  
* Shiawase Man-At-Arms `{python} inc('Nuyen', -4500*.9)`
  * Weapon Mount - Heavy
  * Pop-Out Concealment - Large `{python} inc('Nuyen', -4500/2)`
    * Red Fox
  * Drone Rack (Small) `{python} inc('Nuyen', -3000/2)`
  * Tesla Coil `{python} inc('Nuyen', -15000/2)`
  * Fingertip Compartment `{python} inc('Nuyen', -3000/2)`
    * Monofilament Whip
  * Wrist Shield `{python} inc('Nuyen', -2000/2)`
  * Armor Increase 5 `{python} inc('Nuyen', -25000/2)`
  * Increased Structural Integrity 5 `{python} inc('Nuyen', -25000/2)`
  * Realistic Features 4 `{python} inc('Nuyen', -10000/2)`
  * Hardpoint Small x2 `{python} inc('Nuyen', -1500/2)`
  * Small Weapon Mount x2 `{python} inc('Nuyen', -800/2)`
    * Crimson Wasp x2
  * Secondary Propulsion (Rotor): `{python} inc('Nuyen', -50000/2)`  
  * Increased Sensors 3 `{python} inc('Nuyen', -15000/2)`
  * Retractible Skates x2 `{python} inc('Nuyen',-500/2)`
  * Built-In Utility Kit (Engineering) `{python} inc('Nuyen', -1000/2)`
  * Built-In MedKit `{python} inc('Nuyen', -1000/2)`
  * Accessories
    * Satellite Link
    * Laser Jack

* Federated-Boeing Sky Commander `{python} inc('Nuyen', -12500)`
  * RAM Plating 4
  * ECM 6
  * Enhanced Sensors 2
  * Retrans Unit
  * Satellite Link
  * Integrated Matrix Dock x2 `{python} inc('Nuyen', -800)`
    * M-TOC II
    * Foundation Host (R2)

Drone mods include a 50% discount on mods Yuriko installed herself (DC p. 120). Cyberware is purchased as used/omegaware (50% discount). Shiawase drones include a 10% discount (Smile for the Camera!).

### Electronics

* Software Tag x10 `{python} inc('Nuyen', -100 * 10)`
* Laser Jack x10 `{python} inc('Nuyen', -100 * 10)`
* Satellite Link x2 `{python} inc('Nuyen', -500 * 2)`

### Other Supplies

* Engineering Kit `{python} inc('Nuyen', -500)`
* Medkit R1 `{python} inc('Nuyen', -250)`
* Narcoject x10 `{python} inc('Nuyen', -50 * 10)`
* Cyanide x5 `{python} inc('Nuyen', -70 * 5)`

### SINs & Licenses

* Yuriko Star (R6) `{python} inc_many(('Nuyen', -5000), ('Nuyen', -10000))`
  * Drone License (R6) `{python} inc_many(('Nuyen', -400), ('Nuyen', -800))`
  * Firearms License (R6) `{python} inc_many(('Nuyen', -400), ('Nuyen', -800))`
