<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Downtime Protocols &amp; Common Rules – REIKO // Yuriko Star Portfolio</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/character_log.html" rel="next">
<link href="../chapters/character_sheet.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-6b004faca8ee0f94b3a5dd19405fa1b2.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-80d5c8aa686a4f1f03a54c5fc949acb7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/identity_core.html">Core Character</a></li><li class="breadcrumb-item"><a href="../chapters/rules_and_downtime.html"><span class="chapter-title">Downtime Protocols &amp; Common Rules</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">REIKO // Yuriko Star Portfolio</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">REIKO // Yuriko Star</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Core Character</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/identity_core.html" class="sidebar-item-text sidebar-link"><span class="chapter-title"><strong>IDENTITY_CORE: r31-K0 (“Reiko”)</strong></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/character_sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Character Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/rules_and_downtime.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Downtime Protocols &amp; Common Rules</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/character_log.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Character Career Log</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/twenty_questions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20 Questions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Background Stories</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01 The Weight of Zero.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Weight of Zero</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02 Color Blind Mathematics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title"><strong>Color-Blind Mathematics</strong></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03 The Soul Broker's Stall.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Soul-Broker’s Stall</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04 The War Crime.html" class="sidebar-item-text sidebar-link"><span class="chapter-title"><strong>The War Crime</strong></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05 A SINner's Loan.html" class="sidebar-item-text sidebar-link"><span class="chapter-title"><strong>A SINner’s Loan</strong></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06 The Ghost in the Ledger.html" class="sidebar-item-text sidebar-link"><span class="chapter-title"><strong>The Ghost in the Ledger</strong></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07 Sunday at r3sP@wn.html" class="sidebar-item-text sidebar-link"><span class="chapter-title"><strong>Sunday at r3sP@wn</strong></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Out-of-Session Narratives</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08 Abandoning Tourism.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Abandoning Tourism</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09 Triangulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Triangulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10 Game Theory.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Game Theory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11 Integrating over Infinity.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Integrating over Infinity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12 Defrag.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Defrag</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13 Field Trip.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Field Trip</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14 A Point of Favor.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">A Point of Favor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15 Core.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Core</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16 Faith.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Faith</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17 Sheets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Sheets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/18 The Geometry of a Sieve.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Geometry of the Sieve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/19 Legacy Code.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Legacy Code</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#matrix-decking-protocols" id="toc-matrix-decking-protocols" class="nav-link active" data-scroll-target="#matrix-decking-protocols">Matrix &amp; Decking Protocols</a>
  <ul class="collapse">
  <li><a href="#matrix-attributes" id="toc-matrix-attributes" class="nav-link" data-scroll-target="#matrix-attributes">Matrix Attributes</a></li>
  <li><a href="#matrix-actions" id="toc-matrix-actions" class="nav-link" data-scroll-target="#matrix-actions">Matrix Actions</a></li>
  <li><a href="#network-benefits" id="toc-network-benefits" class="nav-link" data-scroll-target="#network-benefits">Network Benefits</a></li>
  <li><a href="#learned-programs" id="toc-learned-programs" class="nav-link" data-scroll-target="#learned-programs">Learned Programs</a></li>
  <li><a href="#full-matrix-defense" id="toc-full-matrix-defense" class="nav-link" data-scroll-target="#full-matrix-defense">Full Matrix Defense</a></li>
  <li><a href="#home-device-optimization" id="toc-home-device-optimization" class="nav-link" data-scroll-target="#home-device-optimization">Home Device Optimization</a></li>
  <li><a href="#decking-protocols-cheat-sheet" id="toc-decking-protocols-cheat-sheet" class="nav-link" data-scroll-target="#decking-protocols-cheat-sheet">Decking Protocols Cheat Sheet</a></li>
  <li><a href="#buying-gear-in-downtime" id="toc-buying-gear-in-downtime" class="nav-link" data-scroll-target="#buying-gear-in-downtime">Buying Gear in Downtime</a></li>
  </ul></li>
  <li><a href="#drones-rigging" id="toc-drones-rigging" class="nav-link" data-scroll-target="#drones-rigging">Drones &amp; Rigging</a>
  <ul class="collapse">
  <li><a href="#drone-modified-values" id="toc-drone-modified-values" class="nav-link" data-scroll-target="#drone-modified-values">Drone Modified Values</a></li>
  <li><a href="#controlling-drones" id="toc-controlling-drones" class="nav-link" data-scroll-target="#controlling-drones">Controlling Drones</a></li>
  <li><a href="#man-at-arms---crimson-wasp-weapons-array" id="toc-man-at-arms---crimson-wasp-weapons-array" class="nav-link" data-scroll-target="#man-at-arms---crimson-wasp-weapons-array">Man-At-Arms - Crimson Wasp Weapons Array</a></li>
  <li><a href="#sensor-locks" id="toc-sensor-locks" class="nav-link" data-scroll-target="#sensor-locks">Sensor Locks</a></li>
  <li><a href="#rigging-protocols-cheat-sheet" id="toc-rigging-protocols-cheat-sheet" class="nav-link" data-scroll-target="#rigging-protocols-cheat-sheet">Rigging Protocols Cheat Sheet</a></li>
  </ul></li>
  <li><a href="#sprites-resonance" id="toc-sprites-resonance" class="nav-link" data-scroll-target="#sprites-resonance">Sprites &amp; Resonance</a>
  <ul class="collapse">
  <li><a href="#complex-forms" id="toc-complex-forms" class="nav-link" data-scroll-target="#complex-forms">Complex Forms</a></li>
  <li><a href="#registering-sprites" id="toc-registering-sprites" class="nav-link" data-scroll-target="#registering-sprites">Registering Sprites</a></li>
  <li><a href="#sprite-stable" id="toc-sprite-stable" class="nav-link" data-scroll-target="#sprite-stable">Sprite Stable</a></li>
  </ul></li>
  <li><a href="#gear-ammunition" id="toc-gear-ammunition" class="nav-link" data-scroll-target="#gear-ammunition">Gear &amp; Ammunition</a>
  <ul class="collapse">
  <li><a href="#krime-splash-self-defense-ammunition" id="toc-krime-splash-self-defense-ammunition" class="nav-link" data-scroll-target="#krime-splash-self-defense-ammunition">Krime Splash Self-Defense Ammunition</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/identity_core.html">Core Character</a></li><li class="breadcrumb-item"><a href="../chapters/rules_and_downtime.html"><span class="chapter-title">Downtime Protocols &amp; Common Rules</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Downtime Protocols &amp; Common Rules</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This section aggregates core cheat sheets and templates for downtime registration, rigging, decking, and resonance network benefits.</p>
<hr>
<section id="matrix-decking-protocols" class="level2">
<h2 class="anchored" data-anchor-id="matrix-decking-protocols">Matrix &amp; Decking Protocols</h2>
<section id="matrix-attributes" class="level3">
<h3 class="anchored" data-anchor-id="matrix-attributes">Matrix Attributes</h3>
<ul>
<li><strong>Base ASDF</strong>: 3535</li>
<li><strong>Sprite Symbiosis (Crack Sprite)</strong>: 0321 → 3856</li>
<li><strong>Toolbox</strong>: 0010 → 3866</li>
<li><strong>Resonance (7)</strong>: 2113 → 5979</li>
<li><strong>Active Matrix Attributes</strong>: 5979</li>
</ul>
</section>
<section id="matrix-actions" class="level3">
<h3 class="anchored" data-anchor-id="matrix-actions">Matrix Actions</h3>
<p><strong>Base</strong>: Electronics (Software, 5) or Cracking (Hacking, 5)</p>
<ul>
<li>Natural Hacker (Allows RES to replace any attribute in a matrix action): +7</li>
<li>Resonance Focus: +4, 2FV</li>
<li>Overclock: +2 (1 wild)</li>
<li>Teamwork (R8 ally sprite): +4</li>
</ul>
<p><strong>Total</strong>: 22d6 (1 wild, + specialization), FV: 2</p>
</section>
<section id="network-benefits" class="level3">
<h3 class="anchored" data-anchor-id="network-benefits">Network Benefits</h3>
<ul>
<li><strong>Edge Storage</strong>: Capacity 12 (SUB (7) Transcendent Network, 5 M-TOC II)</li>
<li><strong>-6 Noise Reduction</strong>: Designer home device -2, signal scrubber -2, ECM warrior -2</li>
<li><strong>+1 Sensor Rating</strong>: Added to any connected sensor (sensor upgrade)</li>
<li><strong>Resonant Coordination</strong>: Connected characters who use the Send Message action (a Minor Action) among themselves gain a bonus Minor Action immediately afterward.</li>
<li><strong>Smartsoft Array</strong>:
<ul>
<li>Drone Sensor Locks are shared among networked drones (smartsoft).</li>
<li>Target Locked victims cannot spend edge against attacking networked drones.</li>
</ul></li>
<li><strong>Detect Ambush</strong>: -2 Perception test threshold to detect ambush.</li>
<li><strong>Smartguns</strong>: +1 AR to smartlinked weapons.</li>
<li><strong>Encryption</strong>: +1 increased threshold for all incoming Cracking tests.</li>
<li><strong>Tactical Software apps</strong>:
<ul>
<li><em>Artillery Barrage</em>: +1 to Launchers, no rifle/mg/cannon penalties</li>
<li><em>ECM Warrior II</em>: +2 Offensive Cracking tests</li>
<li><em>Sneak-Sneak</em>: +2 Stealth</li>
<li><em>Target Artist</em>: Attack w/o LOS on painted targets</li>
</ul></li>
</ul>
</section>
<section id="learned-programs" class="level3">
<h3 class="anchored" data-anchor-id="learned-programs">Learned Programs</h3>
<section id="cmp-2083-04-hog-wild" class="level4">
<h4 class="anchored" data-anchor-id="cmp-2083-04-hog-wild">CMP 2083-04 | Hog Wild</h4>
<p>2026-Jul-15</p>
<ul>
<li><strong>Nexus Protocol</strong>: Hitchhikers experience UV</li>
<li><strong>Emulator</strong>: Run Commlink Apps
<ul>
<li><em>Personal Assistant (R6)</em>: Full Matrix Defense every round</li>
<li><em>P-ICE Spines</em></li>
<li><em>Social HUD</em>
<ul>
<li>Major action: Conduct matrix search to identify anyone broadcasting a SIN or other credentials</li>
<li>Major action: Conduct matrix search based on facial recognition (tgt must have a SIN on file)</li>
<li>+1 Edge on first social skill test with identified targets</li>
</ul></li>
<li><em>Thermal Mood Reading</em>: Minor action +1 edge on Judge Intentions</li>
<li><em>Comm Spoofer</em>: +1 Edge on Con tests that involve misrepresenting oneself on a comm call</li>
<li><em>Facial Scanner</em>
<ul>
<li>Major action to scan face for nanopaste disguise</li>
<li>+1 situational edge on matrix search to identify recognized targets</li>
</ul></li>
<li><em>MeFeed</em>: +1 situational Edge on matrix search about a person, company, pop culture topic, or current event</li>
</ul></li>
<li><strong>Virtual Machine</strong>: +2 program slots, +1 Matrix Damage taken</li>
<li><strong>Directional Shield</strong>: When in Full Matrix Defense, minor anytime action to add DP to defense pool</li>
<li><strong>Toolbox</strong>: +1 DP</li>
<li><strong>Clearsight</strong></li>
<li><strong>Stealth Autosoft</strong></li>
<li><strong>Coding Facility</strong>
<ul>
<li>Reduces the interval of all programming tests by half (usually 30 minutes)</li>
<li>Grants 1 point of situational edge on programming tests</li>
</ul></li>
</ul>
</section>
</section>
<section id="full-matrix-defense" class="level3">
<h3 class="anchored" data-anchor-id="full-matrix-defense">Full Matrix Defense</h3>
<p>ASDF (from Matrix Attributes)[#matrix-attributes]: 5979</p>
<section id="the-base-matrix-defense-pool-16-dice" class="level4">
<h4 class="anchored" data-anchor-id="the-base-matrix-defense-pool-16-dice">1. The Base Matrix Defense Pool (16 Dice)</h4>
<p>A standard Matrix defense test uses a <strong>Mental Attribute + Matrix Attribute</strong> (most commonly <em>Intuition + Firewall</em> or <em>Willpower + Firewall</em> depending on the incoming Matrix action) [6WB, Page 180].</p>
<ul>
<li><strong>Replacing the Mental Attribute</strong>: Because Reiko has the <strong>Natural Hacker</strong> quality, Reiko can replace the non-Matrix mental attribute with Reiko’s <strong>Resonance (7)</strong> [HnS, Page 84].</li>
<li><strong>Base Pool</strong>: Resonance (7) + Firewall (9) = <strong>16 dice</strong>.</li>
</ul>
</section>
<section id="personal-assistant-rating-6-6-dice" class="level4">
<h4 class="anchored" data-anchor-id="personal-assistant-rating-6-6-dice">2. Personal Assistant Rating 6 (+6 Dice)</h4>
<p>Reiko is running a Rating 6 Personal Assistant commlink app inside Reiko’s Emulator.</p>
<ul>
<li><strong>Rule</strong>: A Personal Assistant app on its default setting constantly takes the Full Defense Matrix action on Reiko’s behalf, which adds its Rating directly to Reiko’s dice pool to resist hostile Matrix actions [HnS, Page 56 / 119].</li>
<li><strong>Bonus</strong>: Rating 6 Personal Assistant = <strong>+6 dice</strong> [HnS, Page 56].</li>
</ul>
</section>
<section id="directional-shield-program-7-dice" class="level4">
<h4 class="anchored" data-anchor-id="directional-shield-program-7-dice">3. Directional Shield Program (+7 Dice)</h4>
<p>Because Reiko’s Personal Assistant is constantly keeping Reiko in a state of Full Matrix Defense, Reiko meets the requirement to activate her Directional Shield program.</p>
<ul>
<li><strong>Rule</strong>: When Reiko has taken the Full Defense action, Reiko can spend a Minor Anytime Action to add Reiko’s <strong>Data Processing</strong> attribute to Reiko’s Matrix defense dice pool against an anticipated Matrix action Reiko is aware of [HnS, Page 56].</li>
<li><strong>Bonus</strong>: Reiko’s Data Processing is <strong>7</strong> = <strong>+7 dice</strong>.</li>
</ul>
</section>
<section id="resonance-focus-4-dice" class="level4">
<h4 class="anchored" data-anchor-id="resonance-focus-4-dice">4. Resonance Focus (+4 Dice)</h4>
<ul>
<li><strong>Bonus</strong>: Utilizing her Resonance Focus adds <strong>+4 dice</strong> directly to Reiko’s Matrix defense tests.</li>
</ul>
</section>
<section id="shield-sprite-power" class="level4">
<h4 class="anchored" data-anchor-id="shield-sprite-power">5. Shield Sprite Power</h4>
<ul>
<li><strong>Bonus</strong>: Shield allows Reiko to add her sprite’s RES (7, see [[registering-sprites#registering-sprites]]) again to the matrix defense tests and opposed complex form / sprite power tests of up to RES icons, personas, or devices under her protection. [HnS p.&nbsp;74]</li>
</ul>
<hr>
</section>
<section id="final-pool-calculation" class="level4">
<h4 class="anchored" data-anchor-id="final-pool-calculation">Final Pool Calculation</h4>
<p><span class="math display">\[\text{2 * Resonance (7)} + \text{Firewall (9)} + \text{Personal Assistant (6)} + \text{Data Processing (7)} + \text{Resonance Echo (4)} = \mathbf{40\text{ Dice}}\]</span></p>
<p>Reiko’s full Matrix defense pool when all of these elements are active is <strong>40 dice</strong>.</p>
</section>
</section>
<section id="home-device-optimization" class="level3">
<h3 class="anchored" data-anchor-id="home-device-optimization">Home Device Optimization</h3>
<ul>
<li>Home Device Tuning: Optimize: set 1 attribute to native; Passive: +1 capacity, +4 rating.</li>
<li>Designer: home dev +1 DP/pilot, 2 Noise Reduction.</li>
<li>M-TOC II:
<ul>
<li>Toolbox: +1 DP.</li>
<li>Home dev: +1 DP.</li>
<li>FW = AI’s FW (9).</li>
</ul></li>
</ul>
</section>
<section id="decking-protocols-cheat-sheet" class="level3">
<h3 class="anchored" data-anchor-id="decking-protocols-cheat-sheet">Decking Protocols Cheat Sheet</h3>
<ul>
<li><strong>Legal Actions</strong>: Electronics + LOG (exceptions noted)</li>
<li><strong>Illegal Actions</strong>: Cracking + LOG (+1 OS, <code>*</code> indicates specialized action)</li>
</ul>
<section id="actions-by-access-level" class="level4">
<h4 class="anchored" data-anchor-id="actions-by-access-level">Actions by Access Level</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Access Level</th>
<th style="text-align: left;">Legal Actions (Electronics + LOG)</th>
<th style="text-align: left;">Illegal Actions (Cracking + LOG)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Outsider / No Access</strong></td>
<td style="text-align: left;">- Enter Host (Minor)<br>- Switch Interface Mode (Minor)<br>- Toggle Silent Running (Minor)<br>- Reconfigure Matrix Attribute (Minor)<br>- *Jack out (Elec + WIL)<br>- Matrix Perception (Elec + INT)<br>- Matrix Search (Elec + INT)<br>- Send Message (Minor)<br>- Full Matrix Defense<br>- Virtual Aim (Minor) / Threat Analysis</td>
<td style="text-align: left;">- Brute Force / <em>Probe<br>- </em>Backdoor Entry / <em>Known Exploit<br>- Masquerade / </em>Metahuman in the Middle<br>- <em>Delayed Command / Popup / </em>Spoof Command<br>- Device Lock / Squelch (Elec + LOG)<br>- Denial of Service (Elec + LOG)<br>- Data Spike / Tarpit<br>- Hide</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>User Access</strong><br><em>(+1 OS/round if forced)</em></td>
<td style="text-align: left;">- Change Icon (Minor)<br>- Edit File / Encrypt File<br>- Hash Check (Elec + LOG)</td>
<td style="text-align: left;">- <em>Crack File<br>- </em>Control Device<br>- Erase Matrix Signature (Elec + LOG)<br>- *Garbage In/Out / Watchdog (Minor)<br>- Disarm Data Bomb (Crack + LOG)<br>- Calibration (Crack + LOG)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Admin Access</strong><br><em>(+3 OS/round if forced)</em></td>
<td style="text-align: left;">- Check OS / Crash Program<br>- Modify Icon (Elec + LOG)</td>
<td style="text-align: left;">- <em>Format Device / </em>Reboot Device<br>- Snoop / <em>Puppet Cyberware (Minor)<br>- </em>Set Data Bomb (Elec + LOG)<br>- *Trace Icon (Elec + INT)<br>- Subvert Infrastructure (Elec + LOG)</td>
</tr>
</tbody>
</table>
</section>
<section id="edge-actions" class="level4">
<h4 class="anchored" data-anchor-id="edge-actions">Edge Actions</h4>
<ul>
<li><strong>(1 Edge)</strong>: Batch Exec, Emergency Boost, Paint Target</li>
<li><strong>(2 Edge)</strong>: Technobabble (Use CHA instead of LOG), Intervene, Hog, Signal Scream</li>
<li><strong>(3 Edge)</strong>: Under the Radar (Action does not increase OS)</li>
</ul>
</section>
</section>
<section id="buying-gear-in-downtime" class="level3">
<h3 class="anchored" data-anchor-id="buying-gear-in-downtime">Buying Gear in Downtime</h3>
<p><strong>Base</strong>: Electronics (5) + Int</p>
<ul>
<li>Natural Hacker (Allows RES to replace any attribute in a matrix action): +7</li>
<li>Resonance Focus: +4</li>
<li>Overclock: +1</li>
<li>Relevant Shopsoft: +1</li>
<li>Teamwork (R8 ally sprite): +4</li>
</ul>
<p><strong>Total</strong>: 22d6 → 5 bought hits</p>
<hr>
</section>
</section>
<section id="drones-rigging" class="level2">
<h2 class="anchored" data-anchor-id="drones-rigging">Drones &amp; Rigging</h2>
<section id="drone-modified-values" class="level3">
<h3 class="anchored" data-anchor-id="drone-modified-values">Drone Modified Values</h3>
<ul>
<li><strong>S. Butler BOD 4(6)</strong>:
<ul>
<li>BOD is 4(6) where structural integrity adds +2.</li>
</ul></li>
<li><strong>S. Butler ARM 0(10)</strong>:
<ul>
<li>ARM is 0(10) total.</li>
<li>Standard armor is supplemented by: SkinShield (+2), RACS activated (+2), InvisiShield (+2), and Wrist shield (+4).</li>
</ul></li>
<li><strong>S. Man-at-Arms BOD 10(15)</strong>:
<ul>
<li>BOD is 10(15) where structural integrity adds +5.</li>
</ul></li>
<li><strong>S. Man-at-Arms ARM 8[17]</strong>:
<ul>
<li>ARM is 8[17] total.</li>
<li>Standard armor is supplemented by: Armor Increase 5 (+5) and Wrist shield (+4).</li>
</ul></li>
</ul>
</section>
<section id="controlling-drones" class="level3">
<h3 class="anchored" data-anchor-id="controlling-drones">Controlling Drones</h3>
<section id="key-qualities-and-rules" class="level4">
<h4 class="anchored" data-anchor-id="key-qualities-and-rules">Key Qualities and Rules</h4>
<ul>
<li><strong>Pilot Origin</strong>: Allows r31k0 to use autosofts up to her <strong>Data Processing</strong> (HnS p 119)</li>
<li><strong>Devices, AR and VR</strong>: Devices controlled remotely via AR use the operator’s physical attributes (SR6B p.&nbsp;180)</li>
<li>For AI, the Matrix Equivalent Attributes table dictates how ASDF form “physical” attributes (BOD [F] AGI [D] REA [S] STR [A]) (HnS p.&nbsp;118)</li>
<li>R31k0’s ally sprite can offer teamwork for shared autosofts (+4) or via Diagnostics (+4 Electronics, Engineering, Piloting)</li>
<li>Sensor Upgrade adds +1 when using sensors</li>
</ul>
</section>
<section id="skills" class="level4">
<h4 class="anchored" data-anchor-id="skills">Skills</h4>
<p>Rating 9 Autosofts: 7 (capped by D)</p>
<ul>
<li>Sprite Symbiosis (Targeting, Electronics, Engineering, and Piloting only): +4</li>
<li>Sensor Upgrade (Clearsight only): +1</li>
</ul>
</section>
<section id="total-pools" class="level4">
<h4 class="anchored" data-anchor-id="total-pools">Total Pools</h4>
<ul>
<li><strong>Pilot/Drive/Crash</strong>: Maneuvering (D, 7) + REA (S, 9) + TW (4) ──&gt; <strong>20</strong></li>
<li><strong>Ramming AR</strong>: Maneuvering (D, 7) + Sensor Rating</li>
<li><strong>DR vs Ramming</strong>: Maneuvering (D, 7) + Armor Rating</li>
<li><strong>Ramming Att/Def</strong>: Pilot Test (See Above)</li>
<li><strong>Weapon AR</strong>: Per Weapon</li>
<li><strong>DR vs Weapons</strong>: Maneuvering (D, 7) + Armor Rating</li>
<li><strong>Weapon Attack</strong>: Targeting (D, 7) + AGI (D, 7) + Sprite (+4) ──&gt; <strong>18</strong></li>
<li><strong>Weapon Defense</strong>: Evasion (D, 7) + REA (S, 9) ──&gt; <strong>16</strong></li>
<li><strong>Perception</strong>: Clearsight (D, 7) + Drone Sensor Rtg + Sensor Upgrade</li>
<li><strong>Stealth</strong>: Stealth (D, 7) + AGI (D, 7) ──&gt; <strong>14</strong></li>
</ul>
<p>To understand how an Artificial Intelligence (AI) character with the <strong>Pilot Origins</strong> quality pilots a drone, we must distinguish between two distinct methods of drone operation: <strong>Jumped-In (Rigging)</strong> and <strong>Remote Control (Un-jumped)</strong> [Hack and Slash, p.&nbsp;119; SR6 Core Rulebook, p.&nbsp;198].</p>
<p>The rules handle these two scenarios differently regarding whether they use standard mental attributes or the AI’s <strong>Matrix Equivalent Attributes</strong> [Hack and Slash, p.&nbsp;118; SR6 Core Rulebook, p.&nbsp;198].</p>
<hr>
</section>
<section id="jumped-in-operation-why-matrix-equivalents-are-bypassed" class="level4">
<h4 class="anchored" data-anchor-id="jumped-in-operation-why-matrix-equivalents-are-bypassed">1. Jumped-In Operation (Why Matrix Equivalents Are Bypassed)</h4>
<p>The <strong>Pilot Origins</strong> quality states:</p>
<blockquote class="blockquote">
<p><em>“The AI may jump into drones and vehicles, controlling them like a rigger. Each level of this quality grants the bonus of a control rig of an equal rating”</em> [Hack and Slash, p.&nbsp;119].</p>
</blockquote>
<p>When an AI character chooses to jump into a drone using this quality, standard rigging rules take over:</p>
<ul>
<li>According to the <strong>Control Rigs and Reiko</strong> rules, a rigger who is jumped into a device uses their mind instead of their meat body [SR6 Core Rulebook, p.&nbsp;198].</li>
<li>Physical attributes are replaced entirely by <strong>Mental attributes</strong> for all jumped-in tests [SR6 Core Rulebook, p.&nbsp;198].</li>
<li>The conversion table for jumped-in riggers dictates the following replacements [SR6 Core Rulebook, p.&nbsp;198]:</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Standard Physical Attribute</th>
<th style="text-align: left;">Jumped-In Mental Attribute</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Body</strong></td>
<td style="text-align: left;">Willpower</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Strength</strong></td>
<td style="text-align: left;">Charisma</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Agility</strong></td>
<td style="text-align: left;">Logic</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Reaction</strong></td>
<td style="text-align: left;">Intuition</td>
</tr>
</tbody>
</table>
<p>Since an AI character natively possesses standard Mental attributes (Willpower, Charisma, Logic, and Intuition) in their character block [Hack and Slash, p.&nbsp;118], they use these <strong>Mental attributes directly</strong> when jumped in.</p>
<ul>
<li><strong>Piloting</strong>: When piloting a jumped-in drone, the test uses Reaction. Because the AI is jumped in, Reaction is replaced by <strong>Intuition</strong>. The AI rolls <strong>Piloting + Intuition</strong> [SR6 Core Rulebook, p.&nbsp;198].</li>
<li><strong>Gunnery/Firing</strong>: When firing a jumped-in drone’s weapons, the test uses Agility. Because the AI is jumped in, Agility is replaced by <strong>Logic</strong>. The AI rolls <strong>Firearms + Logic</strong> [SR6 Core Rulebook, p.&nbsp;198].</li>
</ul>
<p>Because the standard rigging rules bypass physical attributes in favor of mental attributes, the AI does not need to refer to its “Physical Attribute Matrix Equivalents” (Firewall, Sleaze, Data Processing, Attack) in this state.</p>
<hr>
</section>
<section id="remote-control-un-jumped-operation-when-matrix-equivalents-are-used" class="level4">
<h4 class="anchored" data-anchor-id="remote-control-un-jumped-operation-when-matrix-equivalents-are-used">2. Remote Control / Un-jumped Operation (When Matrix Equivalents ARE Used)</h4>
<p>If the AI is <strong>not</strong> jumped into the drone (e.g., they are issuing remote control commands to a drone, or the drone is operating autonomously as an “AI-driven drone” without the AI jumped in), standard remote control rules dictate that the controller’s Physical attributes are used [SR6 Core Rulebook, p.&nbsp;201]. If the AI is controlling the device via VR they use their mental attributes, but if the AI is controlling the device via AR they use their “physical” attributes [Devices, AR and VR, SR6 Core Rulebook, p.&nbsp;180].</p>
<p>Because an AI lacks a physical body, they must substitute their missing Physical attributes using the <strong>Matrix Equivalent Attributes</strong> table [Hack and Slash, p.&nbsp;118]:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Standard Physical Attribute</th>
<th style="text-align: left;">AI Matrix Equivalent Attribute</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Body</strong></td>
<td style="text-align: left;">Firewall</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Agility</strong></td>
<td style="text-align: left;">Data Processing</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Reaction</strong></td>
<td style="text-align: left;">Sleaze</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Strength</strong></td>
<td style="text-align: left;">Attack</td>
</tr>
</tbody>
</table>
<p>In this remote-control scenario, the AI <strong>does</strong> use its Matrix Equivalents:</p>
<ul>
<li><strong>Piloting</strong>: When remotely piloting a drone, the test normally calls for <em>Piloting + Reaction</em>. The AI substitutes Reaction for Sleaze, rolling <strong>Piloting + Sleaze</strong> [Hack and Slash, p.&nbsp;118].</li>
<li><strong>Gunnery/Firing</strong>: When remotely firing a drone’s mounted weapon, the test normally calls for <em>Firearms + Agility</em>. The AI substitutes Agility for Data Processing, rolling <strong>Firearms + Data Processing</strong> [Hack and Slash, p.&nbsp;118].</li>
</ul>
<hr>
</section>
<section id="summary-table-ai-drone-attribute-mapping" class="level4">
<h4 class="anchored" data-anchor-id="summary-table-ai-drone-attribute-mapping">Summary Table: AI Drone Attribute Mapping</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Operation State</th>
<th style="text-align: left;">Attribute Used for Piloting (Reaction equivalent)</th>
<th style="text-align: left;">Attribute Used for Gunnery (Agility equivalent)</th>
<th style="text-align: left;">Rules Authority / Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Jumped-In (via Pilot Origins)</strong></td>
<td style="text-align: left;"><strong>Intuition</strong> (Mental Attribute)</td>
<td style="text-align: left;"><strong>Logic</strong> (Mental Attribute)</td>
<td style="text-align: left;">[SR6 Core Rulebook, p.&nbsp;198]; [Hack and Slash, p.&nbsp;119]</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Remote Control (Un-jumped)</strong></td>
<td style="text-align: left;"><strong>Sleaze</strong> (Matrix Equivalent)</td>
<td style="text-align: left;"><strong>Data Processing</strong> (Matrix Equivalent)</td>
<td style="text-align: left;">[Hack and Slash, p.&nbsp;118]</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="rules-reference-citations" class="level4">
<h4 class="anchored" data-anchor-id="rules-reference-citations">Rules Reference &amp; Citations</h4>
<ul>
<li><strong>[Hack and Slash, p.&nbsp;118]</strong> – AI Character Attribute Block and Matrix Equivalent Attributes.</li>
<li><strong>[Hack and Slash, p.&nbsp;119]</strong> – Pilot Origins Quality &amp; AI-driven drone rules.</li>
<li><strong>[SR6 Core Rulebook, p.&nbsp;198]</strong> – Control Rigs and Reiko, Jumped-In Attribute conversion table.</li>
<li><strong>[SR6 Core Rulebook, p.&nbsp;201]</strong> – Drone Rigging and remote-control command guidelines.</li>
<li><strong>[SR6 Core Rulebook, p.&nbsp;180]</strong> - Devices, AR and VR.</li>
</ul>
</section>
</section>
<section id="man-at-arms---crimson-wasp-weapons-array" class="level3">
<h3 class="anchored" data-anchor-id="man-at-arms---crimson-wasp-weapons-array">Man-At-Arms - Crimson Wasp Weapons Array</h3>
<section id="weapon-profiles-range-profiles" class="level4">
<h4 class="anchored" data-anchor-id="weapon-profiles-range-profiles">1. Weapon Profiles &amp; Range Profiles</h4>
<ul>
<li><strong>rEVOlution Arms Red Fox (Primary)</strong> [Firing Squad, Page 44]:
<ul>
<li><strong>Base DV</strong>: 6P* (Decreases to 3P at Medium and further ranges)</li>
<li><strong>Base Attack Rating</strong>: 14 / 16 / 16 / 9 / — (Close / Near / Medium / Far / Extreme)</li>
</ul></li>
<li><strong>rEVOlution Arms Crimson Wasp (Secondary Link-Fired)</strong> [Firing Squad, Page 44]:
<ul>
<li><strong>Base DV</strong>: 5P* (Decreases to 3P at Medium and further ranges)</li>
<li><strong>Base Attack Rating</strong>: 16 / 14 / 11 / 6 / — (Close / Near / Medium / Far / Extreme)</li>
</ul></li>
</ul>
</section>
<section id="attack-rating-ar-modifications" class="level4">
<h4 class="anchored" data-anchor-id="attack-rating-ar-modifications">2. Attack Rating (AR) Modifications</h4>
<ol type="1">
<li><strong>Smartlink Bonus</strong>: Adding an internal smartlink system to the primary weapon (Red Fox) increases its Attack Rating by <strong>+2 across all available range categories</strong> [SR6 Core Rulebook (Berlin Ed.), Page 262].
<ul>
<li>Red Fox Adjusted AR: <strong>16 / 18 / 18 / 11 / —</strong></li>
</ul></li>
<li><strong>Link-Firing Bonus</strong>: Link-firing multiple weapons increases the primary weapon’s AR by <strong>+1 AR for each additional weapon</strong> added to the attack [Double Clutch, Page 144]. With two Crimson Wasps added, this grants <strong>+2 AR</strong>.
<ul>
<li><strong>Final Attack Rating</strong>: <strong>18 / 20 / 20 / 13 / —</strong></li>
</ul></li>
</ol>
</section>
<section id="damage-value-dv-modifications" class="level4">
<h4 class="anchored" data-anchor-id="damage-value-dv-modifications">3. Damage Value (DV) Modifications</h4>
<p>Under the Link-Firing rules, the base DV is set by the primary weapon (Red Fox: 6P at Close/Near, 3P at Medium/Far) and modified by the secondary weapons (Crimson Wasps):</p>
<ul>
<li><strong>Rule</strong>: Added weapons of DV 5 or higher add <strong>+2 DV</strong> to the attack.</li>
<li><strong>At Close / Near Ranges</strong>
<ul>
<li>Both Wasps are DV 5+, adding +2 DV each (+4 DV total).</li>
<li><strong>Final DV</strong>: 6P + 4 = <strong>10P</strong></li>
</ul></li>
<li><strong>At Medium / Far Ranges</strong>
<ul>
<li>Both Wasps are below DV 5, adding +1 DV each (+2 DV total).</li>
<li><strong>Final DV</strong>: 3P + 2 = <strong>5P</strong></li>
</ul></li>
</ul>
<section id="final-damage-values-dv" class="level5">
<h5 class="anchored" data-anchor-id="final-damage-values-dv">Final Damage Values (DV):</h5>
<p>Because Grunt Groups utilize the base DV of their strongest attacker [SR6 Core Rulebook, Page 114], the damage values do not change.</p>
</section>
</section>
</section>
<section id="sensor-locks" class="level3">
<h3 class="anchored" data-anchor-id="sensor-locks">Sensor Locks</h3>
<section id="establishing" class="level4">
<h4 class="anchored" data-anchor-id="establishing">Establishing</h4>
<ul>
<li>Electronics + Logic (Sensor + Clearsight autosoft in the case of autopilot) vs.&nbsp;Reaction + Piloting (Pilot + Evasion autosoft) (Major)</li>
<li>Biological targets, micro/mini drones, and targets with stealth features gain Edge for the test.</li>
</ul>
</section>
<section id="locked-on-status" class="level4">
<h4 class="anchored" data-anchor-id="locked-on-status">Locked On Status</h4>
<ul>
<li>While suffering this status, the subject cannot spend Edge while defending against attacks originating from the vehicle that established sensor lock.</li>
<li>Locked-on lasts until
<ul>
<li>Cover IV is achieved relative to that vehicle or</li>
<li>until ended by the Break Sensor Lock action.</li>
</ul></li>
</ul>
</section>
<section id="break-sensor-lock" class="level4">
<h4 class="anchored" data-anchor-id="break-sensor-lock">Break Sensor Lock</h4>
<ul>
<li>Reaction + Piloting (Intuition + Reaction in case of metahumans and critters) vs.&nbsp;Electronics + Intuition (Clearsight + Sensor in the case of autopilots) (Major)</li>
<li>Matrix noise in the vicinity of the locked-on target affects only the defense roll.</li>
</ul>
</section>
</section>
<section id="rigging-protocols-cheat-sheet" class="level3">
<h3 class="anchored" data-anchor-id="rigging-protocols-cheat-sheet">Rigging Protocols Cheat Sheet</h3>
<ul>
<li><strong>Pilot/Drive/Crash</strong>: Maneuvering (D, 7) + REA (S, 9) + Teamwork Diagnosis (3) ──&gt; <strong>19</strong></li>
<li><strong>Weapon Attack</strong>: Targeting (D, 7) + AGI (D, 7) + Sprite Symbiosis (4) ──&gt; <strong>18</strong></li>
<li><strong>Perception</strong>: Clearsight (D, 7) + Sprite (4) + Sensor Upgrade (+1) ──&gt; <strong>12 + Sensor</strong></li>
<li><strong>Stealth</strong>: Stealth (D, 7) + AGI (D, 7) + Sprite Symbiosis (4) ──&gt; <strong>18</strong></li>
<li><strong>Defense Test</strong>: Evasion (D, 7) + REA (S, 9) + Sprite Symbiosis (4) ──&gt; <strong>20</strong></li>
<li><strong>Defense Rating</strong>: BOD + ARM</li>
<li><strong>Damage Resistance Test</strong>: BOD</li>
<li><strong>Damage Resistance</strong>: Convert ARM/8 (round down) physical damage (P) into stun (S). Drones ignore stun damage up to their BOD.</li>
<li><strong>Repair</strong>: Electronics(Hardware) + LOG</li>
</ul>
<hr>
</section>
</section>
<section id="sprites-resonance" class="level2">
<h2 class="anchored" data-anchor-id="sprites-resonance">Sprites &amp; Resonance</h2>
<section id="complex-forms" class="level3">
<h3 class="anchored" data-anchor-id="complex-forms">Complex Forms</h3>
<ul>
<li>Includes Sprite Symbiosis bonus: +4.</li>
<li>Includes Resonance Focus: +4 (Fading Value: 2 for use).</li>
</ul>
</section>
<section id="registering-sprites" class="level3">
<h3 class="anchored" data-anchor-id="registering-sprites">Registering Sprites</h3>
<ul>
<li><strong>Minor downtime action</strong>: Register 8levels of sprites (up to R7 sprite)</li>
<li>1 per night’s rest (7 hrs registering, 3 hrs restoration). Must buy hits (SRMG p19)</li>
<li><strong>Outcome</strong>: R7 Modular sprite with 3 services/powers for 3 missions</li>
</ul>
<section id="compiling-phase" class="level4">
<h4 class="anchored" data-anchor-id="compiling-phase">1. Compiling Phase</h4>
<ul>
<li><strong>Pool</strong>: Tasking (6) + RES (7) + Resonance Focus (4) = <strong>17 dice</strong> → <strong>4 Bought Hits</strong>.</li>
<li><strong>Sprite’s Defense</strong>: Level 7 × 2 = <strong>14 dice</strong> → <strong>3 Bought Hits</strong>.</li>
<li><strong>Net Hits</strong>: 4 - 3 = 1 → <strong>1 base service</strong>.</li>
<li><strong>Technoshaman Stream Modification</strong>: Grants +1 additional service on a successful compiling test. Total compiled services = <strong>2 services/powers</strong>.</li>
<li><strong>Fading Value (FV)</strong>: Under core rules, compiling fade is exactly equal to the hits received on the sprite’s defense test = <strong>3</strong>.</li>
<li><strong>Technoshaman Mitigation</strong>: Reduces compiling fade by a flat 2 (3 - 2 = 1).</li>
<li><strong>Fading Resistance</strong>: Willpower (6) + Charisma (4) + Submersion Grade / Sprite Conduit (7) = <strong>17 dice</strong> → <strong>4 Bought Hits</strong>.</li>
<li><strong>Compiling Damage Taken</strong>: 1 FV - 4 hits = <strong>0 Damage</strong>.</li>
</ul>
</section>
<section id="registering-phase" class="level4">
<h4 class="anchored" data-anchor-id="registering-phase">2. Registering Phase</h4>
<ul>
<li><strong>Pool</strong>: Registering (8) + RES (7) + RES Focus (4) = <strong>19 dice</strong> → <strong>4 Bought Hits</strong>.</li>
<li><strong>Sprite’s Defense</strong>: Level 7 × 2 = <strong>14 dice</strong> → <strong>3 Bought Hits</strong>.</li>
<li><strong>Net Hits</strong>: 4 - 3 = 1 → <strong>1 base service</strong>.</li>
<li><strong>Combined Total Services</strong>: 2 (compiled) + 1 (registered) = <strong>3 total services/powers</strong>.</li>
<li><strong>Fading Value (FV)</strong>: Under core rules, registering fade is equal to <em>twice</em> the hits received on the sprite’s defense test (3 x 2 = 6).</li>
<li><strong>Fading Resistance</strong>: Willpower (6) + Charisma (4) + Submersion Grade / Sprite Conduit (7) = <strong>17 dice</strong> → <strong>4 Bought Hits</strong>.</li>
<li><strong>Registering Damage Taken</strong>: 6 FV - 4 hits = <strong>2 boxes of Stun damage</strong>.</li>
</ul>
</section>
<section id="resonance-focus-fading" class="level4">
<h4 class="anchored" data-anchor-id="resonance-focus-fading">3. Resonance Focus Fading</h4>
<p>Because a data structure/focus was used to boost both tests, it incurs its own independent data-structure fade (4 / 2 = 2).</p>
<ul>
<li><strong>Focus Fading Pool</strong>: WIL (6) + LOG (4) = <strong>10 dice</strong> → <strong>2 Bought Hits</strong>.</li>
<li><strong>Damage Taken</strong>: 2 FV - 2 hits = <strong>0 Damage</strong>.</li>
</ul>
</section>
</section>
<section id="sprite-stable" class="level3">
<h3 class="anchored" data-anchor-id="sprite-stable">Sprite Stable</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Mission</th>
<th>Sprites Registered</th>
<th>Tasks Used</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SRM 2081-07</td>
<td>2</td>
<td>0</td>
</tr>
<tr class="even">
<td>SRM 2081-06</td>
<td>2</td>
<td>0</td>
</tr>
<tr class="odd">
<td>CMP 2083-04</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td>5</td>
<td>0</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="gear-ammunition" class="level2">
<h2 class="anchored" data-anchor-id="gear-ammunition">Gear &amp; Ammunition</h2>
<ul>
<li><strong>Ares Predator VI Modifications</strong>:
<ul>
<li>Base: 3P, 10/10/8/–/–</li>
<li>Active Smartlink (+2 Attack Rating to Close/Near/Medium ranges).</li>
<li>Personalized Grip (Ranged) (+1 Attack Rating to Close/Near ranges). (Applies because gun is held.)</li>
<li>Equipped with Silencer (+2 threshold to notice firing).</li>
<li>Ammo: Explosive (4P) or KSSD (5S)</li>
<li><strong>Total</strong> 4P/5S, 13/13/11/–/–</li>
</ul></li>
</ul>
<section id="krime-splash-self-defense-ammunition" class="level3">
<h3 class="anchored" data-anchor-id="krime-splash-self-defense-ammunition">Krime Splash Self-Defense Ammunition</h3>
<p>The outer coating is a friction-liquefying material that is impossible to wash off and paints the target in whatever color Reiko choose when purchasing the ammo. This splash-color is just the jacket for a good degree of glitter-based micro RFID tags that get into the user’s skin through any non-chemical resistant or waterproof outfit, which sparkles while impregnated into their skin while also transmitting to the Matrix. Finally, the major layer, which protects Reiko while the intruder is still in Reikor face: a basic gel round that slams home like every other gel round on the market.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>2D6 RESULT</th>
<th>2D6 RESULT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2 Silver</td>
<td>8 Red</td>
</tr>
<tr class="even">
<td>3 Blue</td>
<td>9 White</td>
</tr>
<tr class="odd">
<td>4 Green</td>
<td>10 Yellow</td>
</tr>
<tr class="even">
<td>5 Orange</td>
<td>11 Indigo</td>
</tr>
<tr class="odd">
<td>6 Pink</td>
<td>12 Rainbow*</td>
</tr>
<tr class="even">
<td>7 Purple</td>
<td></td>
</tr>
</tbody>
</table>
<p>(*Just roll with it and make the targets taste the rainbow!)</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/character_sheet.html" class="pagination-link" aria-label="Character Sheet">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Character Sheet</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/character_log.html" class="pagination-link" aria-label="Character Career Log">
        <span class="nav-page-text"><span class="chapter-title">Character Career Log</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>