REF_MAP = {
    "soft_con_performance": "Performance",
    "soft_con_navigation": "Navigation",
    "soft_con_maneuvering": "Maneuvering",
    "soft_con_evasion": "Evasion",
    "soft_con_clearsight": "Clearsight",
    "targeting": "Targeting",
    "stealth_auto": "Stealth",
    "soft_tracking": "Tracking",
    "personal_assistant": "Personal Assistant",
    "social_hud": "Social HUD",
    "thermal_mood_reading": "Thermal Mood Reading",
    "vocal_tension_detection": "Vocal Tension Detection",
    "overclock": "Overclock",
    "hitchhiker": "Hitchhiker",
    "trace": "Trace",
    "toolbox": "Toolbox",
    "virtual_machine": "Virtual Machine",
    "signal_scrubber": "Signal Scrubber",
    "directional_shield": "Directional Shield",
    "decryption": "Decryption",
    "defense_pods": "Defense Pods",
    "fork": "Fork",
    "nexus_protocol_program": "Nexus Protocol Program",
    "smart_rig": "Smartsoft",
    "soft_navigation": "Navigation",
    "soft_engineering": "Engineering",
    "sneak_sneak": "Sneak-Sneak"
}

SW_CAT_MAP = {
    "BIOTECH": "Autosofts", 
    "CLEARSIGHT": "Autosofts", 
    "EVASION": "Autosofts", 
    "MANEUVERING": "Autosofts", 
    "STEALTH": "Autosofts", 
    "TARGETING": "Autosofts", 
    "CLOSE COMBAT": "Autosofts", 
    "ELECTRONICS": "Autosofts", 
    "ENGINEERING": "Autosofts",
    "ARMOR": "Hacking", 
    "BIOFEEDBACK": "Hacking", 
    "DECRYPTION": "Hacking", 
    "DEFENSE PODS": "Hacking", 
    "DIRECTIONAL SHIELD": "Hacking", 
    "EXPLOIT": "Hacking", 
    "FORK": "Hacking", 
    "OVERCLOCK": "Hacking", 
    "SCRUBBER": "Hacking", 
    "TRACE": "Hacking",
    "HITCHHIKER": "Hacking", 
    "SIGNAL SCRUBBER": "Hacking", 
    "BABY MONITOR": "Hacking",
    "CODE BUDDY": "Commlink Apps", 
    "FACIAL SCANNER": "Commlink Apps", 
    "MANNEQUIN": "Commlink Apps",
    "MEFEED": "Commlink Apps", 
    "P-ICE SPINES": "Commlink Apps", 
    "PERSONAL ASSISTANT": "Commlink Apps",
    "SOCIAL HUD": "Commlink Apps", 
    "VOCAL TENSION DETECTION": "Commlink Apps",
    "AUTOSOFT HOST": "Basic", 
    "BROWSE": "Basic", 
    "EDIT": "Basic", 
    "EMULATOR": "Basic", 
    "ENCRYPTION": "Basic", 
    "SNEAK-SNEAK": "Basic",
    "TOOLBOX": "Basic", 
    "VIRTUAL MACHINE": "Basic"
}
